# Generated by Django 4.2.1 on 2023-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='users/cover_photos/cover-photo-4.PNG', null=True, upload_to='users/cover_photos'),
        ),
    ]
