# Generated by Django 4.2.1 on 2023-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/profile_pictures/male-1.png', null=True, upload_to='users/profile_pictures'),
        ),
    ]
